//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int administrator_id { get; set; }
        public string adminstrator_Name { get; set; }
        public int user_id { get; set; }
        public int adminstrator_Age { get; set; }
        public string adminstrator_Gender { get; set; }
        public string adminstrator_job { get; set; }
    
        public virtual User User { get; set; }
    }
}
