//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int attendance_id { get; set; }
        public int SS_ID { get; set; }
        public int student_id { get; set; }
        public System.DateTime adate { get; set; }
        public int status { get; set; }
    }
}
