//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int class_ID { get; set; }
        public string class_name { get; set; }
        public int class_capacity { get; set; }
        public string class_Type { get; set; }
        public int building_ID { get; set; }
    }
}
