//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complain
    {
        public int complain_id { get; set; }
        public string complain_Info { get; set; }
        public int parent_ID { get; set; }
        public Nullable<int> administrator_ID { get; set; }
        public int Status { get; set; }
    }
}
