//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark
    {
        public int mark_ID { get; set; }
        public Nullable<double> year_wok { get; set; }
        public Nullable<double> final_exam_grade { get; set; }
        public Nullable<int> student_ID { get; set; }
        public Nullable<int> subject_ID { get; set; }
        public int year { get; set; }
    }
}
