//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int message_id { get; set; }
        public int sender_ID { get; set; }
        public int receiver_ID { get; set; }
        public string message_text { get; set; }
        public string about_text { get; set; }
    }
}
