//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int student_ID { get; set; }
        public string student_name { get; set; }
        public string student_Address { get; set; }
        public int student_Age { get; set; }
        public string student_Gender { get; set; }
        public int studentNational_ID { get; set; }
        public int user_id { get; set; }
        public int parent_ID { get; set; }
        public int grade_ID { get; set; }
        public int class_ID { get; set; }
    
        public virtual Parent Parent { get; set; }
        public virtual User User { get; set; }
    }
}
