//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_S
    {
        public int T_S_ID { get; set; }
        public Nullable<int> subject_ID { get; set; }
        public Nullable<int> teacher_ID { get; set; }
    }
}
